### ISSUE TITLE
Zombie tunnels left over after shutdown

### ISSUE THREAD

**Issue by geekdave** [TestArmada/crows-nest#7]
After running:

```
./node_modules/.bin/pm2 stop all
```

...it appears that if the tunnels can't be gracefully shut down in time, `pm2` just exits uncleanly leaving behind zombie tunnels.  These then prevent new tunnels from being created when a subsequent run of:

```
./node_modules/.bin/pm2 start ./bin/supervise --kill-timeout 600000 --silent -- --tunnels 10 --rollingRestart
```

...is invoked:

```
PM2        | 2016-09-30 22:40:15: ===============================================================================
PM2        | 2016-09-30 22:40:15: --- New PM2 Daemon started ----------------------------------------------------
PM2        | 2016-09-30 22:40:15: Time                 : Fri Sep 30 2016 22:40:15 GMT+0000 (UTC)
PM2        | 2016-09-30 22:40:15: PM2 version          : 2.0.12
PM2        | 2016-09-30 22:40:15: Node.js version      : 4.4.7
PM2        | 2016-09-30 22:40:15: Current arch         : x64
PM2        | 2016-09-30 22:40:15: PM2 home             : /home/XXXXXXXX/.pm2
PM2        | 2016-09-30 22:40:15: PM2 PID file         : /home/XXXXXXXX/.pm2/pm2.pid
PM2        | 2016-09-30 22:40:15: RPC socket file      : /home/XXXXXXXX/.pm2/rpc.sock
PM2        | 2016-09-30 22:40:15: BUS socket file      : /home/XXXXXXXX/.pm2/pub.sock
PM2        | 2016-09-30 22:40:15: Application log path : /home/XXXXXXXX/.pm2/logs
PM2        | 2016-09-30 22:40:15: Process dump file    : /home/XXXXXXXX/.pm2/dump.pm2
PM2        | 2016-09-30 22:40:15: Concurrent actions   : 4
PM2        | 2016-09-30 22:40:15: SIGTERM timeout      : 1600
PM2        | 2016-09-30 22:40:15: ===============================================================================
PM2        | 2016-09-30 22:40:15: Starting execution sequence in -fork mode- for app name:supervise id:0
PM2        | 2016-09-30 22:40:15: App name:supervise id:0 online
PM2        | 2016-09-30 22:40:21: App [supervise] with id [0] and pid [11105], exited with code [255] via signal [S
IGINT]
PM2        | 2016-09-30 22:40:21: Starting execution sequence in -fork mode- for app name:supervise id:0
PM2        | 2016-09-30 22:40:21: App name:supervise id:0 online
PM2        | 2016-10-03 01:55:27: Stopping app:supervise id:0
PM2        | 2016-10-03 01:55:27: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:27: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:27: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:27: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:27: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:28: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:28: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:28: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:28: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:28: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:28: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:28: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:28: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:28: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:28: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:29: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:29: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:29: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:29: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:29: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:29: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:29: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:29: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:29: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:29: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:30: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:30: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:30: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:30: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:30: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:30: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:30: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:30: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:30: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:30: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:31: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:31: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:31: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:31: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:31: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:31: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:31: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:31: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:31: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:31: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:32: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:32: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:32: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:32: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:32: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:32: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:32: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:32: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:32: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:32: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:33: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:33: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:33: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:33: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:33: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:33: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:33: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:33: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:33: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:33: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:34: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:34: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:34: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:34: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:34: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:34: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:34: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:34: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:34: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:34: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:35: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:35: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:35: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:35: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:35: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:35: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:35: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:35: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:35: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:35: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:36: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:36: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:36: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:36: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:36: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:36: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:36: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:36: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:36: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:36: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:37: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:37: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:37: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:37: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:37: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:37: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:37: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:37: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:37: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:37: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:38: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:38: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:38: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:38: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:38: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:38: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:38: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:38: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:38: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:38: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:39: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:39: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:39: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:39: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:39: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:39: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:39: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:39: Process with pid 11123 still not killed, retrying...
PM2        | 2016-10-03 01:55:39: App [supervise] with id [0] and pid [11123], exited with code [0] via signal [SIG
INT]
PM2        | 2016-10-03 05:30:37: Starting execution sequence in -fork mode- for app name:supervise id:0
PM2        | 2016-10-03 05:30:37: App name:supervise id:0 online

/home/XXXXXXXX/.pm2/logs/supervise-error-0.log last 1000 lines:
0|supervis | Error: spawn ETXTBSY
0|supervis |     at exports._errnoException (util.js:873:11)
0|supervis |     at ChildProcess.spawn (internal/child_process.js:298:11)
0|supervis |     at exports.spawn (child_process.js:362:9)
0|supervis |     at run (/home/XXXXXXXX/sauce-tunnel-supervisor/node_modules/sauce-connect-launcher/lib/sauce-connect
-launcher.js:293:11)
0|supervis |     at /home/XXXXXXXX/sauce-tunnel-supervisor/node_modules/async/lib/async.js:725:23
0|supervis |     at /home/XXXXXXXX/sauce-tunnel-supervisor/node_modules/async/lib/async.js:166:37
0|supervis |     at fn (/home/XXXXXXXX/sauce-tunnel-supervisor/node_modules/async/lib/async.js:711:34)
0|supervis |     at /home/XXXXXXXX/sauce-tunnel-supervisor/node_modules/async/lib/async.js:1164:16
0|supervis |     at /home/XXXXXXXX/sauce-tunnel-supervisor/node_modules/async/lib/async.js:166:37
0|supervis |     at /home/XXXXXXXX/sauce-tunnel-supervisor/node_modules/async/lib/async.js:671:43
0|supervis |     at /home/XXXXXXXX/sauce-tunnel-supervisor/node_modules/async/lib/async.js:167:37
0|supervis |     at /home/XXXXXXXX/sauce-tunnel-supervisor/node_modules/async/lib/async.js:1160:30
0|supervis |     at /home/XXXXXXXX/sauce-tunnel-supervisor/node_modules/async/lib/async.js:52:16
0|supervis |     at /home/XXXXXXXX/sauce-tunnel-supervisor/node_modules/async/lib/async.js:1160:30
0|supervis |     at /home/XXXXXXXX/sauce-tunnel-supervisor/node_modules/sauce-connect-launcher/lib/sauce-connect-laun
cher.js:118:9
```

**Comment by archlichking** [comment]
`--kill-timeout 600000` is added to avoid the not-enough-time-to-kill-all-tunnels behavior as much as possible, but it won't solve the issue. It might still leave the zombie tunnel(s) if the kill-timeout isn't enough for `crows-nest` to terminate all tunnels. 

One thing we can do is, check zombie tunnels and hard kill them before launching new tunnels.

**Comment by archlichking** [comment]
https://github.com/TestArmada/crows-nest/pull/13
